name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Package and upload
      run: |
        zip function.zip lambda_function.py
        aws s3 cp function.zip s3://${{ secrets.S3_BUCKET_PROD }}/${{ secrets.S3_PATH_PROD }}

    - name: Deploy to production
      run: |
        aws cloudformation deploy \
          --stack-name ${{ secrets.CF_STACK_NAME_PROD }} \
          --template-file infrastructure/cloudformation/lambda-ec2-shutdown.yml \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
            LambdaFunctionName=${{ secrets.LAMBDA_NAME_PROD }} \
            LambdaCodeBucket=${{ secrets.S3_BUCKET_PROD }} \
            LambdaCodeKey=${{ secrets.S3_PATH_PROD }}
